import type { CelestialBody } from "@/types";

export const planets: CelestialBody[] = [
  {
    id: "earth",
    name: "Earth",
    gravity: 9.81,
    relativeGravity: 1.0,
    color: "#4da6ff",
    surfaceColor: "#2d6e2d",
    skyColor: "#87ceeb",
    emoji: "🌍",
    lightTemp: "neutral",
    funFacts: [
      "Earth is the only planet not named after a Greek or Roman god!",
      "A day on Earth is actually 23 hours, 56 minutes, and 4 seconds long.",
      "Earth is the densest planet in our entire solar system!",
      "About 71% of Earth's surface is covered in water.",
      "Earth's atmosphere protects us from about 100 tons of space debris every day!",
    ],
  },
  {
    id: "moon",
    name: "Moon",
    gravity: 1.62,
    relativeGravity: 0.165,
    color: "#c0c0c0",
    surfaceColor: "#888888",
    skyColor: "#000000",
    emoji: "🌙",
    lightTemp: "cool",
    funFacts: [
      "You could jump about 6 times higher on the Moon than on Earth!",
      "The Moon has no atmosphere, so the sky is always black — even during the day.",
      "Footprints on the Moon will last for millions of years because there's no wind!",
      "The Moon is slowly drifting away from Earth — about 1.5 inches per year.",
      "A day on the Moon lasts about 29.5 Earth days!",
    ],
  },
  {
    id: "mars",
    name: "Mars",
    gravity: 3.72,
    relativeGravity: 0.379,
    color: "#e07040",
    surfaceColor: "#c1440e",
    skyColor: "#d4a574",
    emoji: "🔴",
    lightTemp: "warm",
    funFacts: [
      "Mars has the tallest volcano in the solar system — Olympus Mons is 3 times taller than Mount Everest!",
      "A year on Mars is 687 Earth days — almost two Earth years!",
      "Mars has dust storms that can cover the entire planet for months!",
      "Mars sunsets are blue! The opposite of Earth's orange sunsets.",
      "You'd weigh about 1/3 of your Earth weight on Mars.",
    ],
  },
  {
    id: "jupiter",
    name: "Jupiter",
    gravity: 24.79,
    relativeGravity: 2.528,
    color: "#e0a050",
    surfaceColor: "#c49a6c",
    skyColor: "#d4a060",
    emoji: "🟠",
    lightTemp: "warm",
    funFacts: [
      "Jupiter is so big that over 1,300 Earths could fit inside it!",
      "On Jupiter, you'd feel like you were carrying two of yourself on your back!",
      "Jupiter's Great Red Spot is a storm bigger than Earth that has lasted over 350 years!",
      "Jupiter has no solid surface — it's made of gas all the way down!",
      "A day on Jupiter is only about 10 hours long, making it the fastest-spinning planet!",
    ],
  },
  {
    id: "sun",
    name: "Sun",
    gravity: 274.0,
    relativeGravity: 27.94,
    color: "#ffcc00",
    surfaceColor: "#ff6600",
    skyColor: "#ff4400",
    emoji: "☀️",
    lightTemp: "warm",
    funFacts: [
      "The Sun's gravity is so strong that a 100-pound kid would weigh almost 2,800 pounds!",
      "The Sun is so big that about 1.3 million Earths could fit inside it!",
      "Light from the Sun takes about 8 minutes to reach Earth.",
      "The surface of the Sun is about 10,000°F — hot enough to melt anything!",
      "The Sun is actually a giant ball of hydrogen and helium gas.",
    ],
  },
  {
    id: "pluto",
    name: "Pluto",
    gravity: 0.62,
    relativeGravity: 0.063,
    color: "#a0d0e0",
    surfaceColor: "#d4c5a9",
    skyColor: "#1a1a2e",
    emoji: "❄️",
    lightTemp: "cool",
    funFacts: [
      "On Pluto, you could jump about 16 times higher than on Earth!",
      "Pluto is so far away that sunlight takes over 5 hours to reach it.",
      "Pluto is smaller than Earth's Moon!",
      "A year on Pluto is 248 Earth years — it hasn't even completed one orbit since it was discovered!",
      "Pluto has a heart-shaped glacier on its surface made of frozen nitrogen.",
    ],
  },
  {
    id: "europa",
    name: "Europa",
    gravity: 1.315,
    relativeGravity: 0.134,
    color: "#80d0d0",
    surfaceColor: "#b8d4d4",
    skyColor: "#000000",
    emoji: "🧊",
    lightTemp: "cool",
    funFacts: [
      "Europa has a giant ocean of liquid water hidden under its icy surface!",
      "Scientists think Europa might be one of the best places to find alien life!",
      "Europa's ice shell is estimated to be 10-15 miles thick.",
      "Europa is one of Jupiter's 95 known moons!",
      "The surface of Europa is one of the smoothest in the solar system — almost no mountains or craters.",
    ],
  },
  {
    id: "titan",
    name: "Titan",
    gravity: 1.352,
    relativeGravity: 0.138,
    color: "#d09030",
    surfaceColor: "#a07830",
    skyColor: "#cc8833",
    emoji: "🟤",
    lightTemp: "warm",
    funFacts: [
      "Titan is the only moon in our solar system with a thick atmosphere!",
      "Titan has lakes and rivers — but they're made of liquid methane, not water!",
      "If you could stand on Titan, the gravity is so low and the air so thick that you could strap on wings and fly!",
      "Titan's atmosphere is so hazy that you can't see the Sun from the surface.",
      "Titan is bigger than the planet Mercury!",
    ],
  },
];

export function getPlanetById(id: string): CelestialBody | undefined {
  return planets.find((p) => p.id === id);
}
